// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl8BfgKEoEGjATvs-_f4Jw_BwPcAS1ENQ',
    appId: '1:794554892971:web:f2451a2e258868c3b5adee',
    messagingSenderId: '794554892971',
    projectId: 'socialfriction-6a9fe',
    authDomain: 'socialfriction-6a9fe.firebaseapp.com',
    storageBucket: 'socialfriction-6a9fe.firebasestorage.app',
    measurementId: 'G-GKL1V5E66S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCYfwegMoRXOZNEdXtg8V9ld5Ga2XfWBg',
    appId: '1:794554892971:android:23a7dbd98fce7673b5adee',
    messagingSenderId: '794554892971',
    projectId: 'socialfriction-6a9fe',
    storageBucket: 'socialfriction-6a9fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0XjKFg3ZYg7KNem0bgm-k_gM30DUiq9g',
    appId: '1:794554892971:ios:7abd00f27aba81d1b5adee',
    messagingSenderId: '794554892971',
    projectId: 'socialfriction-6a9fe',
    storageBucket: 'socialfriction-6a9fe.firebasestorage.app',
    androidClientId: '794554892971-6rg4n8jnmdpob4a35hjbq180d1prnpfr.apps.googleusercontent.com',
    iosClientId: '794554892971-8ugqtorvv4tt2h0gegh5hrbmekdm3jns.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialFriction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0XjKFg3ZYg7KNem0bgm-k_gM30DUiq9g',
    appId: '1:794554892971:ios:7abd00f27aba81d1b5adee',
    messagingSenderId: '794554892971',
    projectId: 'socialfriction-6a9fe',
    storageBucket: 'socialfriction-6a9fe.firebasestorage.app',
    androidClientId: '794554892971-6rg4n8jnmdpob4a35hjbq180d1prnpfr.apps.googleusercontent.com',
    iosClientId: '794554892971-8ugqtorvv4tt2h0gegh5hrbmekdm3jns.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialFriction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl8BfgKEoEGjATvs-_f4Jw_BwPcAS1ENQ',
    appId: '1:794554892971:web:a5f15c9798cf8412b5adee',
    messagingSenderId: '794554892971',
    projectId: 'socialfriction-6a9fe',
    authDomain: 'socialfriction-6a9fe.firebaseapp.com',
    storageBucket: 'socialfriction-6a9fe.firebasestorage.app',
    measurementId: 'G-YXK4B8VJ69',
  );

}